# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: dev server ci-cd

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Make Directory for delivery
      run: mkdir deploy
      
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy/
      
    - name: Make zip
      run: zip -r -qq -j ./dev-build.zip ./deploy
      
    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      run: |
        aws s3 cp \
        --region ap-northeast-2 \
        --acl private \
        ./dev-build.zip s3://sso-code-bucket/

    - name: Deploy Code
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      run: |
            aws deploy create-deployment \
            --application-name github-actions \
            --deployment-group-name dev-sso \
            --file-exists-behavior OVERWRITE \
            --s3-location bucket=sso-code-bucket,bundleType=zip,key=dev-build.zip \
            --region ap-northeast-2
